services:
  auth_api:
    build: .
    container_name: auth_api
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis_db
    command: >
      sh -c "sleep 5 &&
             python manage.py makemigrations auth_api &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 myproject.asgi:application"

  db:
    image: postgres:15
    container_name: auth_db
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis_db:
    image: redis:7
    container_name: auth_redis
    ports:
      - "6377:6379"

volumes:
  postgres_data:
