# Generated by Django 4.2.25 on 2025-10-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_signuprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuprequest',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='signuprequest',
            name='username',
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='full_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='mobile_no',
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='region',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
