# Generated by Django 4.2.25 on 2025-10-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_remove_signuprequest_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
